### ISSUE TITLE
Better docs on common use cases please

### ISSUE THREAD

**Issue by adavie1** [kysonic/riot-mui#36]
Firstly, I really like what you've done here- makes it really fast to create pages.

However, I'm having difficulty with some very simple things: can't seem to get the value from input fields, etc.  I've tried the Roitjs documented methods, jQuery etc. None seem to work.

In the end, I had to resort to standard HTML to get things working.

What would solve the issue for me, is more examples of common usage scenarios.

Lastly, how to integrate this with the material grid system? I've included the materialize.css stylesheet and i can use the rest of the materialize css grids, etc. But the input field has a double underline when selected.

**Comment by kysonic** [comment]
@adavie1, 

Thanks. I'm not sure that it is possible to integrate some grid system painless... Because riot does not have method to encapsulate styles of its components. Unfortunately it cannot be implemented right now easily. So you have to work with sources of components to change styles which could conflict with styles of your grid system. 

About documentation - I got it. Could you please provide more examples about what problems you had? I will check out docs and examples of material-input for sure. Are there another components you had problem with?

**Comment by kysonic** [comment]
@adavie1 ,

And extra idea: If you want to use some grid system and some material components with it I recommend you yo take a look on [Polymer](https://www.polymer-project.org/1.0/). It is web component based framework helping you to build components with style encapsulation.
